name: flashcard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_swiper_view: ^1.1.8
  dio: ^5.4.3+1
  image_picker: ^1.0.8
  # file_picker: ^8.0.0+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  # path_provider: ^2.1.3
  card_swiper: ^3.0.1
  loop_page_view: ^1.2.5
  audioplayers: ^5.2.1
  http: ^1.2.0
  path_provider: ^2.1.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/onboarding1.png
    - asset/onboarding2.png
    - asset/onboarding3.png
    - asset/signin.png
    - asset/signup.png
    - asset/profile.png
    - asset/search-line.png
    - asset/Edit.png
    - asset/edit2.png
    - asset/Logout.png
    - asset/image.png
    - asset/Upload.png
    - asset/box.png
    - asset/Plus.png
    - asset/edit_icon.png
    - asset/EmptyState.png
    - asset/arrow.png
    - asset/Delete.png
    - asset/Grid.png
    - asset/Grid2.png
    - asset/shuffle.png
    - asset/sound.png
    - asset/Frame.png
    - asset/Frame-2.png
    - asset/cat1.png
    - asset/cat2.png
    - asset/cat3.png
    - asset/playsound.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: asset/font/BricolageGrotesque-Regular.ttf
        - asset: asset/font/BricolageGrotesque-Bold.ttf
          # style: italic
          # weight: bold
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
